theme: minima
title: This is my blog
author: GuilhermeOPC
email: guilherme.opc@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello. I'm Guilherme and I will be a dev quit so soon

# social links
twitter_username: otguilherme # DO NOT include the @ character, or else the build will fail!
github_username:  GuilhermeOPC # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
